name: thing_toast
description:
  "Implementation of Material 3 Expressive Toast. Inspired by Sonner from Shandcn.
  4 Types of Toast: Succes, Info, Warning, and Error."
version: 1.2.0
repository: https://github.com/thing_code/thing_toast

environment:
  sdk: ^3.13.4
  flutter: ">=1.17.0"

workspace:
  - example

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
